Genre_List = [
    {"label": "Action", "value": "Action"},
    {"label": "Adventure", "value": "Adventure"},
    {"label": "Animation", "value": "Animation"},
    {"label": "Comedy", "value": "Comedy"},
    {"label": "Crime", "value": "Crime"},
    {"label": "Documentary", "value": "Documentary"},
    {"label": "Drama", "value": "Drama"},
    {"label": "Family", "value": "Family"},
    {"label": "Fantasy", "value": "Fantasy"},
    {"label": "Foreign", "value": "Foreign"},
    {"label": "History", "value": "History"},
    {"label": "Horror", "value": "Horror"},
    {"label": "Music", "value": "Music"},
    {"label": "Mystery", "value": "Mystery"},
    # {"label": "N/A", "value": "N/A"},
    {"label": "Romance", "value": "Romance"},
    {"label": "Science Fiction", "value": "Science Fiction"},
    {"label": "TV Movie", "value": "TV Movie"},
    {"label": "Thriller", "value": "Thriller"},
    {"label": "War", "value": "War"},
    {"label": "Western", "value": "Western"},
]


actor_high_rated_movie_df_cols = [
    "actor_name",
    "genre_name",
    "above_9_count",
    "above_8_count",
    "above_7_count",
    "above_6_count",
    "above_5_count",
    "below_5_count",
]
